name: Build (development)
on: 
    push: 
        branches:
            - dev
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2.1.4
              with:
                node-version: 12
            - name: tsc test
              uses: alexthemaster/action-build-typescript@v1.2.1
